//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleverbitLikeUnlikePagesApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thread
    {
        public int ThreadId { get; set; }
        public Nullable<int> SecretPoll { get; set; }
        public Nullable<int> LikeCount { get; set; }
        public Nullable<int> DislikeCount { get; set; }
    }
}
